### ISSUE TITLE
Complex search structures

### ISSUE THREAD

**Issue by DonaldTsang** [mserajnik/hydrusrvue#7] opened 2019-01-28 07:46 UTC
For future reference, these are the pages of search cheatsheets
- https://gelbooru.com/index.php?page=help&topic=cheatsheet (Gelbooru)
- https://danbooru.donmai.us/wiki_pages/43049 (Danbooru)
- https://e621.net/help/show/cheatsheet (Danbooru)
- https://yande.re/wiki/show?title=cheat_sheet_extended (Moebooru)
- https://konachan.com/help/cheatsheet (Moebooru)
- https://rule34.xxx/index.php?page=help&topic=cheatsheet (a type of Shimme)
- https://hypnohub.net/help/cheatsheet (a type of MyImouto)
- https://chan.sankakucomplex.com/help/cheatsheet (Sankaku)

The ones above all have similar syntax, and the odd-one-out in the booru-sphere is Derpibooru with a complex structure ( see https://derpibooru.org/search/syntax for more)

I will add some extra detail specs for a "unified standard" for the above list

**Comment by mserajnik** [comment] 2019-01-28 08:31
I'm not sure about the intent of this issue, but let me get this out of the way before you waste too much of your time:

---

Again, sorry, but like with the API, I'm not interested in following any kind of arbitrary standard here. I'm calling it _arbitrary_ because this obviously is only the same for all those softwares because no one bothered to think of something better (but it looks like Derpibooru is at least trying, so points for that, even though it's not apparent to me from their syntax docs how they handle sorting).

This is booru-_inspired_ (meaning that it borrows concepts from established boorus). But this does not mean that I want it to follow everything other softwares did to the letter and/or try to conform to a common "standard". The way you enter multiple tags and handle sorting is completely different (and I would argue, _better_) to all of those boorus whose frontends all seem to exist from 10+ years ago.

The lack of _trying_ to provide a comfortable user experience alone (which becomes apparent, when you need to sort via `sort:updated:desc` instead of having a separate input element to choose the sorting) is enough reason for me not wanting to follow anything those boorus have done before in terms to searching.

**Comment by mserajnik** [comment] 2019-01-28 13:12
> AND, OR search functions

`AND` is the basic tag search and has been in since day 1. `OR` is out of scope. I'm not interested in adding it as it would complicate things __a lot__.

> NOT search functions

Already implemented as described in the hydrusrv docs (e.g., `-house`).

> wildcards

[In progress](https://github.com/mserajnik/hydrusrv/issues/17#issuecomment-457962661).

> namespaces

Supported since day 1 as described in the hydrusrv docs (e.g., `creator:lorem`).

> metadata searching

Already implemented as described in the hydrusrv docs (e.g., `width>1000` or `id=42`).

> hash-based searching

Already implemented as described in the docs (`hash=<hash>`), although only SHA-256 since hydrus server doesn't generate other formats. And generating the rest ourselves with every update would be insane, so not interest.

---

Once the wildcard tag searching is released (in the coming days), this project is pretty much considered finished. All of these things can be combined in a search. You can search for specific tags while at the same time wildcarding namespaces, excluding tags, excluding whole namespaces, limiting to certain file dimensions and sizes and sorting the result by namespaces in the order of your choosing. I think this is more than enough, in fact, more than any other single booru I am aware of features (they basically all lack the extensive sorting options).

Other than `OR` searching (which I'd never add), there's not much else I could do with the data hydrus server provides without doing costly calculations when syncing (and that's out of the question).

**Comment by DonaldTsang** [comment] 2019-01-28 14:25
> Other than OR searching (which I'd never add), there's not much else I could do with the data hydrus server provides without doing costly calculations when syncing (and that's out of the question).

I am pretty sure that Hydrus will have `OR` search function in 6 months as the dev insures us.

**Comment by mserajnik** [comment] 2019-01-28 14:40
> I am pretty sure that Hydrus will have `OR` search function as the dev insures us (my guess is in 3~6 months).

Yes, he's already confirmed that. Doesn't affect hydrusrv in any way though, we can't use any of the hydrus search functionality for a multitude of obvious reasons (like pagination and the simple fact that hydrus server doesn't feature any search API to begin with, that's all in the client).

It's certainly useful for managing collections (which hydrus does) where you might need to find files via `OR` tags to do something with them (e..g., add a tag `uncensored` to all files that have `meta:uncensored` __or__ `meta:decensored`).

For simply _consuming_ content, I can't think of many use cases where you either couldn't find a workaround (e.g., via wildcards) or where it wouldn't be used to "solve" a content issue (missing tags). And in such a case, I would point to hydrus again, because that's what it's made for.

In any case, `OR` searches are off the table for hydrusrv.

**Comment by DonaldTsang** [comment] 2019-01-28 14:47
> Edit: For the features you want, it might be better to wait for the hydrus client API since that will probably feature its full search functionality (and I'm sure someone will write a frontend for it).
Understood

**Closed** 2019-01-28 14:50 UTC
